### ISSUE TITLE
Change of License?

### ISSUE THREAD

**Issue by techdragon** [vivi90/python-vmc#2]
The Creative Commons organisation does not recommend the use of CC licenses on software or hardware. "The only categories of works for which CC does not recommend its licenses are [computer software](https://creativecommons.org/faq/#Can_I_apply_a_Creative_Commons_license_to_software) and hardware." - From https://creativecommons.org/faq/#what-are-creative-commons-licenses

Would you be opposed to changing the license to a more appropriate license for a software project? (MIT, Apache2, GPLv3, etc)

**Comment by vivi90** [comment]
@techdragon I will switch over to the LGPLv3 and after that to the AGPLv3 license.


Then i will move the entire repository to [CodeBerg](https://codeberg.org/vivi90) permanently 🙂 
I invite you to follow me to CodeBerg, because of:
https://sfconservancy.org/blog/2022/jun/30/give-up-github-launch

**Comment by techdragon** [comment]
LGPLv3 is a good pick. (I don't personally recommend AGPLv3 as anything but a "license of last resort" for when nothing else could potentially give the desired outcome, but this isn't the place for me to preach my views on legal risk theory and its chilling effect on long term code reuse. Your code means that above all its your choice 😎 👍 )

When you move this to CodeBerg, I'd encourage you to leave this repo online with a prominent notice at the top of the readme instead of overwriting the entire content of the readme or deleting the repo, both things I've seen other people moving off GitHub choose to do... since many developers may not find your code without it turning up in GitHub's code search. I know for sure that I would not have found it had it not been on GitHub in its present form. Google and other search engines don't do a great job indexing most source code hosting platforms, making it easier to discover library/utility code by searching individual code hosting platforms for such relevant libraries.

**Comment by vivi90** [comment]
> LGPLv3 is a good pick. (I don't personally recommend AGPLv3 as anything but a "license of last resort" for when nothing else could potentially give the desired outcome, but this isn't the place for me to preach my views on legal risk theory and its chilling effect on long term code reuse. Your code means that above all its your choice 😎 👍 )

Why not AGPL? 🙂 

> [..] instead of overwriting the entire content of the readme or deleting the repo [..]

It's not completely deleted.
The Git history is still there and you just need to revert the last commit 🙂 
I deleted it in the last commit, so hopefully the crawler of CoPilot and other products think, it's worthless.

> [..] since many developers may not find your code without it turning up in GitHub's code search. I know for sure that I would not have found it had it not been on GitHub in its present form. Google and other search engines don't do a great job indexing most source code hosting platforms, making it easier to discover library/utility code by searching individual code hosting platforms for such relevant libraries.

That's absolutely no problem for me 🙂 
Lib's will get hosted on the suitable place for it (this project on [PyPi](https://pypi.org), if it's ready for productional usage).
For my other projects i will just share links, if required, so it doesn't matter where it's hosted.

Might be fine to be found by others as an passionate developer and earn stars or follows.
But that's not the reason why i hosted my repositories on GitHub.
It's just: I have an problem, i try to solve it and i need an place to host it. Nothing else 😄 
And since [CodeBerg](https://codeberg.org) now supports also CI with woodpecker, is hosted on european servers and provided by an non-profit organization, so yeah it seems an much better place for my projects than GitHub to me.
